apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 66%
  selector:
    matchLabels: 
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      # affinity:
      #   podAntiAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - podAffinityTerm:
      #         labelSelector:
      #           matchLabels:
      #             app: node-app
      #         topologyKey: kubernetes.io/hostname
      #       weight: 50
      containers:
        - name: node-app
          image: conormgomes/liatrio_demo:1729295805
          ports:
            - containerPort: 80
          imagePullPolicy: Always