apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-app
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - port: 80 #where service will listen for traffic, other pods communicate through this
      targetPort: 80 #internal communication with pod responsible for handling traffic, where service sends request