name: Pipeline

on:
  push:
    branches: [ main, workflow-testing ]

jobs:
  generate-variables:
    runs-on: ubuntu-22.04
    outputs: 
      TIME_NOW: ${{ env.TIME_NOW }}
      sha_short: ${{ env.sha_short }}
      node_change: ${{ env.node_change }}
      deploy_change: ${{ env.deploy_change }}
      service_change: ${{ env.service_change }}
      hpa_change: ${{ env.hpa_change }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate tag number and commit hash
        run: |
          echo "TIME_NOW=$(date +%s)" >> "$GITHUB_ENV"
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Check file changes
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Generate change bools
        run: |
          echo "node_change=${{ (contains(steps.changed-files.outputs.modified_files, 'index.js')) || (contains(steps.changed-files.outputs.modified_files, 'package.json')) || (contains(steps.changed-files.outputs.modified_files, 'package-lock.json')) || (contains(steps.changed-files.outputs.modified_files, 'Dockerfile')) }}" >> $GITHUB_ENV
          echo "deploy_change=${{ contains(steps.changed-files.outputs.modified_files, 'deployment.yaml')}}" >> $GITHUB_ENV
          echo "service_change=${{ contains(steps.changed-files.outputs.modified_files, 'service.yaml')}}" >> $GITHUB_ENV
          echo "hpa_change=${{ contains(steps.changed-files.outputs.modified_files, 'hpa.yaml')}}" >> $GITHUB_ENV

  docker-build-test-push:
    needs: [ generate-variables ]
    if: ${{ needs.generate-variables.outputs.node_change == 'true' }}
    uses: ./.github/workflows/build_test_push.yaml
    with:
      TIME_NOW: ${{ needs.generate-variables.outputs.TIME_NOW }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy-to-k8s:
    needs: [ generate-variables, docker-build-test-push ]
    if: ${{ (needs.docker-build-test-push.result == success) || (needs.generate-variables.outputs.deploy_change == 'true') || (needs.generate-variables.outputs.service_change == 'true') || (needs.generate-variables.outputs.hpa_change == 'true') }}
    uses: ./.github/workflows/k8s.yaml
    with:
      TIME_NOW: ${{ needs.generate-variables.outputs.TIME_NOW }}
      sha_short: ${{ needs.generate-variables.outputs.sha_short }}
      node_change: ${{ needs.generate-variables.outputs.node_change }}
      deploy_change: ${{ needs.generate-variables.outputs.deploy_change }}
      service_change: ${{ needs.generate-variables.outputs.service_change }}
      hpa_change: ${{ needs.generate-variables.outputs.hpa_change }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}