name: Test, Build, and Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t git-image

      - name: Spin up container
        run: docker run -dp 172.17.0.1:80:80 git-image

      - name: Run tests
        id: testing
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Log in to Docker
        env:
          docker_user: ${{secrets.DOCKER_USERNAME}}
          docker_pass: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $docker_user -p $docker_pass

      - name: Generate tag number and commit hash
        run: |
          echo "TIME_NOW=$(date +%s)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Push to Docker Hub
        run: |
          docker tag git-image conormgomes/liatrio_demo:$TIME_NOW
          docker push conormgomes/liatrio_demo:$TIME_NOW

      - name: Edit deployment.yaml
        run: |
          cp ./kube_configs/deployment.yaml ./kube_configs/deployment_old.yaml
          sed -r -i 's/conormgomes\/liatrio_demo:.*/conormgomes\/liatrio_demo:'$TIME_NOW'/' ./kube_configs/deployment.yaml
      
      - name: Authenticate AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install kubectl
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install kubectl --classic

      - name: Connect AWS to kubectl
        run: |
          aws eks update-kubeconfig --region us-west-2 --name test-cluster

      - name: Update deployment with new image
        run: |
          kubectl apply -f ./kube_configs/deployment.yaml

      - name: Change deployment.yaml in repo
        run: |
          git config --global user.name 'conormgomes'
          git config --global user.email 'gomesconor@gmail.com'
          git add ./kube_configs/deployment.yaml ./kube_configs/deployment_old.yaml
          git commit -m "Automated update of deployment.yaml for Commit ${{ env.sha_short }} [skip actions]"
          git push origin main

      - name: Check files changes
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            kube_configs/**
            index.js
      
      - name: Did they change?
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "IT'S WORKING"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done