name: Test, Build, and Push Docker image

on:
  push:
    branches: [ main, k8s-workflow ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t git-image

      - name: Spin up container
        run: docker run -dp 172.17.0.1:80:80 git-image

      - name: Run tests
        id: testing
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Confirm tests
        if: steps.testing.outcome != 'success'
        run: exit 1

      - name: Log in to Docker
        env:
          docker_user: ${{secrets.DOCKER_USERNAME}}
          docker_pass: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $docker_user -p $docker_pass

      - name: Generate tag number
        run: echo "TIME_NOW=$(date +%s)" >> $GITHUB_ENV

      - name: Push to Docker Hub
        run: |
          docker tag git-image conormgomes/liatrio_demo:$TIME_NOW
          docker push conormgomes/liatrio_demo:$TIME_NOW
          docker tag git-image conormgomes/liatrio_demo:latest
          docker push conormgomes/liatrio_demo:latest
      
      - name: Authenticate AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install kubectl
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install kubectl --classic

      - name: Connect AWS to kubectl
        run: |
          aws eks update-kubeconfig --region us-west-2 --name test-cluster

      - name: Update deployment with new image
        run: |
          kubectl set image deployment/node-deployment node-app=conormgomes/liatrio_demo:$TIME_NOW